### ISSUE TITLE
All types are inferred as string

### ISSUE THREAD

**Issue by pincman** [asteasolutions/zod-to-openapi#267] opened 2024-10-29 12:35 UTC
Type inference error for request and response: I tried to build an OpenAPI using this library in combination with hono.js and Next.js. However, after defining the schema, I discovered that when calling the API from the Next.js client, type errors occur. All request parameters and response types have become string types, including date and number types.

response type error
```ts
export const postSchema = z
    .object({
        id: z.string(),
        title: z.string(),
        thumb: z.string(),
        summary: z.string().nullable().optional(),
        keywords: z.string().nullable().optional(),
        description: z.string().nullable().optional(),
        slug: z.string().nullable().optional(),
        body: z.string(),
        createdAt: z.coerce.date(),
        updatedAt: z.coerce.date(),
    })
    .strict();
app .openapi(
            createRoute({
                tags: ['文章操作'],
                method: 'get',
                path: '/:item',
                request: {
                    params: z.object({
                        item: z.string(),
                    }),
                },
                responses: {
                    200: {
                        content: {
                            'application/json': {
                                schema: postSchema,
                            },
                        },
                        description: '文章查询结果',
                    },
                },
            }),
            async (c) => {
                try {
                    const { item } = c.req.param();
                    const result = await queryPostItem(item);
                    return c.json(result) as any;
                } catch (error) {
                    return c.json({ error }, 500);
                }
            },
        )
```

```tsx
 const result = await apiClient.api.posts[':item'].$get({ param: { item: params.item } });
    if (!result.ok) return notFound();
    const post = await result.json();
// ...
  <div>
                            <span>
                                <AiOutlineCalendar />
                            </span>
                            <time className="tw-ellips">
                                {!isNil(post.updatedAt)
                                    ? formatChineseTime(post.updatedAt)
                                    : formatChineseTime(post.createdAt)}
                            </time>
                        </div>
```
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/c96c6bd7-bfeb-43e9-8d7d-c0fd6013d0fc">
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/d63325b4-b50d-4551-a3bc-69b2fd91964d">

request type error

```ts
export const postPaginateQuerySchema = z.object({
    page: z.coerce.number().optional().openapi({ type: 'number' }),
    limit: z.coerce.number().optional().openapi({ type: 'number' }),
    orderBy: z.enum(['asc', 'desc']).optional(),
});
export const postPaginateResultSchema = z.object({
    items: z.array(postSchema),
    meta: z.object({
        itemCount: z.coerce.number(),
        totalItems: z.coerce.number(),
        perPage: z.coerce.number(),
        totalPages: z.coerce.number(),
        currentPage: z.coerce.number(),
    }),
});
export type PostPaginate = z.infer<typeof postPaginateResultSchema>;
```
```tsx
 const res = await apiClient.api.posts.$get({
        query: { page, limit },
    });
    const { items, meta } = (await res.json()) as any as PostPaginate;

    if (meta.totalPages && meta.totalPages > 0 && page > meta.totalPages) {
        return redirect('/');
    }
// ...
```
<img width="1555" alt="image" src="https://github.com/user-attachments/assets/6e2a5fd4-dc4c-4320-8795-3a196b4c11d5">

**Comment by AGalabov** [comment] 2024-11-04 08:39
@pincman this is not an issue with our library in terms of your integration.

1. The `date`. `z.date()` does validate dates. However in terms of "specification" (Open API) there is no date representation - there is only a string with some specific formatting but it still a string.
2. The second screenshot with page and limit is probably correct - I think the documentation would say that it is a number. However in general over HTTP requests the query parameters are all strings. So I imagine what you are seeing is caused by the Next.JS (or something else on your stack) type system and it has nothing to do with our library.


I am going to close this issue but if you happen to notice that is wrongly generated feel free to open up a new issue or reopen this one. Good luck!

**Closed by AGalabov** 2024-11-04 08:39 UTC

**Comment by paulwongx** [comment] 2024-12-04 04:01
I'm encountering the same issue. @pincman how did you go about resolving response values that are dates/numbers being converted to strings?
