### ISSUE TITLE
Request body only allows 'application/json'

### ISSUE THREAD

**Issue by ryan-mars** [asteasolutions/zod-to-openapi#34] opened 2022-09-27 22:12 UTC
Currently we only allow request bodies with media type `application/json`

I would like to use `application/x-www-form-urlencoded`. Unfortunately these are still quite common, including in the [OAuth spec](https://www.rfc-editor.org/rfc/rfc6749#section-4.4.2). 

`application/json` is hard-coded here:
https://github.com/asteasolutions/zod-to-openapi/blob/5fc40ede62ec4891a899469d941f20eb11ea26a2/src/openapi-generator.ts#L423-L425

I'm not sure how to modify the existing openapi extension to stay consistent with the current design.

**Comment by ryan-mars** [comment] 2022-09-27 23:27
Perhaps it would make sense to modify the current request implementation of body to more closely match the spec of multiple request bodies keyed by content type.

**Comment by blade2005** [comment] 2022-09-28 17:39
> Perhaps it would make sense to modify the current request implementation of body to more closely match the spec of multiple request bodies keyed by content type.

If so this issue would become a duplicate of #31 

It's a good idea

**Comment by ryan-mars** [comment] 2022-09-29 02:36
If we can update #31 to include requests and responses, then yes that would be fantastic.

**Comment by AGalabov** [comment] 2022-09-29 09:12
@ryan-mars @blade2005 I'd keep them separate for now since their implementation may vary. I'm about to open a PR for #31 now, so this would be handled in a separate PR. However since those would both be breaking changes they would go out as the same release (v2.0.0)

**Closed** 2022-10-03 18:55 UTC

**Comment by AGalabov** [comment] 2022-10-03 19:24
This feature should now be available as part of the [v2.0.0 release](https://github.com/asteasolutions/zod-to-openapi/releases/tag/v2.0.0).
