### ISSUE TITLE
Named for openapi schema extension doesn't extracts into components.schema

### ISSUE THREAD

**Issue by artsiommiksiuk** [asteasolutions/zod-to-openapi#273] opened 2024-11-25 19:57 UTC
```ts
export const PublicUserSchema = z.object({
    id: z.string().uuid(),
    avatarUrl: z.string().optional(),
    name: z.string(),
    email: z.string(),
}).openapi("User");

export const AgentUserStateSchema = z.enum(["active", "inactive"]).openapi("UserState");
export const AgentUserSchema = PublicUserSchema.extend({
    state: AgentUserStateSchema,
}).openapi("User");

export getUser = (): RouteConfig => ({
        summary: "Get user",
        tags,
        method: "get",
        operationId: "getUser",
        path: "/users/{userId}",
        request: {
            params: z.object({
                userId: UserIdPathParameter,
            })
        },
        responses: {
            "200": {
                description,
                content: {
                     "application/json": {
                           schema: AgentUserSchema,
                     }
                }
           }
    })
```

This leads to that schema being inlined into request as:

```yaml
/users/{userId}:
    get:
      summary: Get user
      tags:
        - user
      operationId: getUser
      parameters:
        - schema:
            $ref: "#/components/schemas/UserId"
          required: true
          in: path
          name: userId
      responses:
        "200":
          description: User
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/User"
                  - allOf:
                      - $ref: "#/components/schemas/User"
                      - type: object
                        properties:
                          state:
                            $ref: "#/components/schemas/UserState"
                        required:
                          - state
```

I'd expect it to be as well extracted to components.schema.

So, I'd like it to be extracted into components.schema part.

As another possibility I'm looking for, is to avoid allOf usage for extension, and have a hard merged objects. Is it possible?

**Comment by artsiommiksiuk** [comment] 2024-11-25 20:07
Okay, seems like I figured answer to my question.

if I do the hard copy, instead of `.extend()`, 

```ts
export const AgentUserSchema = z.object({
    ...PublicUserSchema.shape,
    state: AgentUserStateSchema,
}).openapi("User");
```

Then it produces hard type (without anyOf).

Still, with the inline part, I think it is a bug of itself.

**Comment by AGalabov** [comment] 2024-12-03 15:32
@artsiommiksiuk thank you for the report. The problem is that you are reusing the `openapi` "name" - you have User twice. If you have for example:

```ts
export const AgentUserSchema = PublicUserSchema.extend({
  state: AgentUserStateSchema,
}).openapi('AgentUser');
```

you would have a separate schema defined that extends the current User schema.

And I believe that this is how it should behave. If we were to override with the last usage of the "User" registration the we would need to inline the base User schema properties `id` + `avatarUrl` + `name` + `email` as otherwise there wouldn't be anything to reference (User would be a circular reference).

I am since going to close this issue. If you have any other questions and/or issues feel free to ask!

**Closed by AGalabov** 2024-12-03 15:32 UTC
